// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVSQL_VERSION_H
#define KDEVSQL_VERSION_H

#include <kdeversion.h>

#define KDEVSQL_MAJOR_VERSION @KDEVSQL_VERSION_MAJOR@
#define KDEVSQL_MINOR_VERSION @KDEVSQL_VERSION_MINOR@
#define KDEVSQL_PATCH_VERSION @KDEVSQL_VERSION_PATCH@

#define KDEVSQL_VERSION_STR "@KDEVSQL_VERSION_MAJOR@.@KDEVSQL_VERSION_MINOR@.@KDEVSQL_VERSION_PATCH@"

#define KDEVSQL_VERSION KDE_MAKE_VERSION(@KDEVSQL_VERSION_MAJOR@, @KDEVSQL_VERSION_MINOR@, @KDEVSQL_VERSION_PATCH@)

#endif
